[project]
name = "flake8-odoo-nameguard"
version = "0.3.0"
description = "Flake8 plugin to enforce Odoo field naming conventions"
authors = [{ name = "tao-thewarat", email = "thewarat.tao19@gmail.com" }]
readme = "README.md"
requires-python = ">=3.8"
dependencies = ["flake8 >= 6.0.0"]

[project.entry-points."flake8.extension"]
ODN = "odoo_naming:OdooFieldNameChecker"
